import fetch from 'node-fetch'; // Ensure node-fetch is available or handle appropriately

const webhookUrl = 'https://discord.com/api/webhooks/1381353293200101547/jilB77WVJYYJqTfco23-YzTn0JpMZipSRY0xwoMkdb29MDe7PzqNyQHMummuYbUGrUCu';

interface EmbedField {
  name: string;
  value: string;
  inline?: boolean;
}

interface Embed {
  title: string;
  description?: string;
  color?: number;
  fields?: EmbedField[];
  footer?: {
    text: string;
  };
  timestamp?: string;
}

export async function sendErrorToDiscord(error: Error, additionalInfo?: string, userDescription?: string): Promise<void> {
  console.log(`Sending error to Discord: ${error.message}`); // Temporary logging

  const embed: Embed = {
    title: `Error Report: ${error.name || 'Unknown Error'}`,
    description: error.message,
    color: 0xff0000, // Red color for errors
    fields: [],
    footer: {
      text: 'Error report generated by Dione App',
    },
    timestamp: new Date().toISOString(),
  };

  if (userDescription) {
    embed.fields?.push({
      name: 'User Description',
      value: userDescription,
      inline: false,
    });
  }

  if (additionalInfo) {
    embed.fields?.push({
      name: 'Additional Info',
      value: additionalInfo,
      inline: false,
    });
  }

  if (error.stack) {
    // Discord embed fields have a 1024 character limit.
    // Stack traces can be long, so we might need to truncate or split them.
    const stackTrace = error.stack.length > 1000 ? error.stack.substring(0, 1000) + '...' : error.stack;
    embed.fields?.push({
      name: 'Stack Trace',
      value: `\`\`\`
${stackTrace}
\`\`\``, // Using markdown for code block
      inline: false,
    });
  }

  try {
    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ embeds: [embed] }),
    });

    if (response.ok) {
      console.log('Error report sent to Discord successfully.');
    } else {
      const errorBody = await response.text();
      console.error(`Failed to send error report to Discord. Status: ${response.status}, Body: ${errorBody}`);
    }
  } catch (networkError) {
    console.error('Network error when trying to send error report to Discord:', networkError);
  }
}
