export const mediaMimeMap: Record<string, string> = {
	"3g2": "video/3gpp2",
	"3gp": "video/3gpp",
	aac: "audio/aac",
	aif: "audio/aiff",
	aifc: "audio/aiff",
	aiff: "audio/aiff",
	amr: "audio/amr",
	apng: "image/apng",
	avi: "video/x-msvideo",
	avif: "image/avif",
	bmp: "image/bmp",
	flac: "audio/flac",
	flv: "video/x-flv",
	gif: "image/gif",
	heic: "image/heic",
	heif: "image/heif",
	ico: "image/x-icon",
	jfif: "image/jpeg",
	jpeg: "image/jpeg",
	jpg: "image/jpeg",
	m4a: "audio/mp4",
	m4b: "audio/mp4",
	m4p: "audio/mp4",
	m4v: "video/x-m4v",
	mkv: "video/x-matroska",
	mov: "video/quicktime",
	mp3: "audio/mpeg",
	mp4: "video/mp4",
	mpg: "video/mpeg",
	mpeg: "video/mpeg",
	oga: "audio/ogg",
	ogg: "audio/ogg",
	opus: "audio/ogg",
	png: "image/png",
	svg: "image/svg+xml",
	tif: "image/tiff",
	tiff: "image/tiff",
	weba: "audio/webm",
	webm: "video/webm",
	webp: "image/webp",
	wav: "audio/wav",
};

export const previewableMediaExtensions = new Set(Object.keys(mediaMimeMap));

export const unsupportedExtensions = new Set(
	[
		"exe",
		"dll",
		"bin",
		"dat",
		"iso",
		"pdf",
		"zip",
		"rar",
		"7z",
		"gz",
		"tgz",
		"bz2",
		"xz",
		"tar",
		"ttf",
		"otf",
		"woff",
		"woff2",
		"eot",
	].filter((extension) => !previewableMediaExtensions.has(extension)),
);

export const fileIconColorMap: Record<string, string> = {
	bash: "text-lime-300",
	bats: "text-lime-300",
	c: "text-blue-300",
	cc: "text-blue-300",
	config: "text-stone-300",
	cpp: "text-blue-300",
	cs: "text-violet-300",
	csharp: "text-violet-300",
	css: "text-sky-200",
	cxx: "text-blue-300",
	docker: "text-sky-300",
	env: "text-stone-300",
	go: "text-cyan-300",
	graphql: "text-purple-300",
	js: "text-amber-300",
	json: "text-emerald-300",
	jsonc: "text-emerald-300",
	jsx: "text-amber-300",
	jfif: "text-rose-300",
	svg: "text-purple-300",
	apng: "text-sky-200",
	avif: "text-emerald-300",
	m4a: "text-indigo-300",
	m4b: "text-indigo-300",
	m4p: "text-indigo-300",
	m4v: "text-purple-300",
	mpg: "text-orange-300",
	mpeg: "text-orange-300",
	"3gp": "text-orange-300",
	"3g2": "text-orange-300",
	flv: "text-orange-300",
	aif: "text-teal-300",
	aifc: "text-teal-300",
	aiff: "text-teal-300",
	amr: "text-indigo-300",
	heic: "text-emerald-300",
	heif: "text-emerald-300",
	tif: "text-amber-200",
	tiff: "text-amber-200",
	weba: "text-cyan-300",
	lock: "text-neutral-300",
	markdown: "text-pink-300",
	md: "text-pink-300",
	mdx: "text-pink-300",
	mjs: "text-amber-300",
	mts: "text-sky-300",
	mp3: "text-teal-300",
	mp4: "text-indigo-300",
	php: "text-indigo-300",
	plist: "text-amber-200",
	proto: "text-cyan-300",
	ps1: "text-lime-300",
	png: "text-sky-200",
	py: "text-sky-300",
	jpeg: "text-rose-300",
	jpg: "text-rose-300",
	gif: "text-purple-300",
	bmp: "text-amber-200",
	webp: "text-green-300",
	ico: "text-blue-200",
	wav: "text-cyan-300",
	ogg: "text-purple-300",
	oga: "text-purple-300",
	opus: "text-purple-300",
	flac: "text-teal-300",
	aac: "text-indigo-300",
	mov: "text-purple-300",
	avi: "text-rose-300",
	mkv: "text-orange-300",
	webm: "text-emerald-300",
	rb: "text-rose-300",
	rs: "text-orange-300",
	scss: "text-fuchsia-300",
	sh: "text-lime-300",
	sql: "text-amber-300",
	toml: "text-purple-300",
	ts: "text-sky-300",
	tsx: "text-sky-300",
	txt: "text-neutral-300",
	yaml: "text-purple-300",
	yml: "text-purple-300",
	default: "text-neutral-300",
};

export const invalidNamePattern = /[<>:"/\\|?*\x00-\x1F]/;

export const languageByExtension: Record<string, string> = {
	bat: "bat",
	c: "c",
	cc: "cpp",
	cpp: "cpp",
	cs: "csharp",
	cts: "typescript",
	docker: "dockerfile",
	env: "properties",
	go: "go",
	graphql: "graphql",
	gql: "graphql",
	h: "cpp",
	hpp: "cpp",
	html: "html",
	ini: "ini",
	java: "java",
	js: "javascript",
	json: "json",
	jsonc: "json",
	jsx: "javascript",
	lock: "json",
	md: "markdown",
	mdx: "markdown",
	mjs: "javascript",
	mts: "typescript",
	php: "php",
	plist: "xml",
	proto: "protobuf",
	ps1: "powershell",
	py: "python",
	rb: "ruby",
	rs: "rust",
	scss: "scss",
	sh: "shell",
	sql: "sql",
	toml: "toml",
	ts: "typescript",
	tsx: "typescript",
	txt: "plaintext",
	vue: "vue",
	yaml: "yaml",
	yml: "yaml",
};
